BEGIN;

ALTER TYPE "AuditAction" ADD VALUE 'INGEST_UPLOAD';
ALTER TYPE "AuditAction" ADD VALUE 'INGEST_MAPPING_CONFIRMED';
ALTER TYPE "AuditAction" ADD VALUE 'INGEST_VALIDATED';
ALTER TYPE "AuditAction" ADD VALUE 'INGEST_NORMALIZED';
ALTER TYPE "AuditAction" ADD VALUE 'INGEST_READY';
ALTER TYPE "AuditAction" ADD VALUE 'INGEST_COMMIT';
ALTER TYPE "AuditAction" ADD VALUE 'INGEST_FAILURE';

ALTER TYPE "AuditResourceType" ADD VALUE 'IMPORT_JOB';
ALTER TYPE "AuditResourceType" ADD VALUE 'SOURCE_FILE';

COMMIT;
