name: Local
variables:
  - name: baseUrl
    value: http://localhost:4000
  - name: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbXNhbzQwejAwMDAwendnMXE1cXFhNG9vIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg1NjA2ODAzLCJleHAiOjE3ODU2MDc3MDN9.QK0I4vUGpa2-D4ZQsZRZJiwOFRwNDkObrEDy4Ulwbw4
  - name: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbXNhbzQwejAwMDAwendnMXE1cXFhNG9vIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4NjExNjc2OCwiZXhwIjoxNzg2MTE3NjY4fQ.E7B12tIuqNRNVdhlnibKysHeIQvJ_rBiZnfTZ3PHdbY
