export enum AuditActorType {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
}

export enum AuditAction {
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS',
  AUTH_REFRESH_FAILURE = 'AUTH_REFRESH_FAILURE',
  COMPANY_CREATE = 'COMPANY_CREATE',
  COMPANY_UPDATE = 'COMPANY_UPDATE',
  COMPANY_DELETE = 'COMPANY_DELETE',
  MEMBER_ADD = 'MEMBER_ADD',
  MEMBER_ROLE_UPDATE = 'MEMBER_ROLE_UPDATE',
  MEMBER_REMOVE = 'MEMBER_REMOVE',
  MEMBER_SELF_LEAVE = 'MEMBER_SELF_LEAVE',
  OWNERSHIP_TRANSFER = 'OWNERSHIP_TRANSFER',
  FINANCIAL_STATEMENT_CREATE = 'FINANCIAL_STATEMENT_CREATE',
  FINANCIAL_STATEMENT_UPDATE = 'FINANCIAL_STATEMENT_UPDATE',
  FINANCIAL_STATEMENT_DELETE = 'FINANCIAL_STATEMENT_DELETE',
  LINE_ITEM_CREATE = 'LINE_ITEM_CREATE',
  LINE_ITEM_UPDATE = 'LINE_ITEM_UPDATE',
  LINE_ITEM_DELETE = 'LINE_ITEM_DELETE',
  LINE_ITEMS_REPLACE = 'LINE_ITEMS_REPLACE',
  INGEST_UPLOAD = 'INGEST_UPLOAD',
  INGEST_MAPPING_CONFIRMED = 'INGEST_MAPPING_CONFIRMED',
  INGEST_VALIDATED = 'INGEST_VALIDATED',
  INGEST_NORMALIZED = 'INGEST_NORMALIZED',
  INGEST_READY = 'INGEST_READY',
  INGEST_COMMIT = 'INGEST_COMMIT',
   INGEST_PARSED = 'INGEST_PARSED',
   INGEST_PARSE_FAILURE = 'INGEST_PARSE_FAILURE',
   INGEST_STAGED = 'INGEST_STAGED',
   INGEST_STAGE_FAILURE = 'INGEST_STAGE_FAILURE',
   INGEST_FAILURE = 'INGEST_FAILURE',
}

export enum AuditResourceType {
  USER = 'USER',
  COMPANY = 'COMPANY',
  COMPANY_MEMBER = 'COMPANY_MEMBER',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  FINANCIAL_LINE_ITEM = 'FINANCIAL_LINE_ITEM',
  AUTH_SESSION = 'AUTH_SESSION',
  IMPORT_JOB = 'IMPORT_JOB',
  SOURCE_FILE = 'SOURCE_FILE',
}

export enum AuditResult {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}
